permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

filter: 'category'

# 作者信息
author: 
  name: 千里冰封 ice1000
  email: ice1000kotlin@foxmail.com
  zhihu: https://www.zhihu.com/people/qian-li-bing-feng-36
  github: https://github.com/ice1000
  gitbook: https://www.gitbook.com/@ice1000/dashboard

# 站点信息
title: 冰封的时间之域
description: 千里冰封的时间之域
url: https://ice1000.github.io
email: ice1000kotlin@foxmail
# rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/images/ice.jpg
favicon: /assets/images/nc.jpg

sass:
  style: compressed
gems:
  - jekyll-sitemap
