permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

filter: 'category'

# 作者信息
author: 
  name: kangkangkang or kang
  email: 1650028256@qq.com
  
  github: https://github.com/kangkangkang
  

# 站点信息
title: 燎原之处
description: 邪恶的烈火燎原
url: https://kangkangkang.github.io
email: 1650028256@qq.com
# rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/images/ice.jpg
favicon: /assets/images/nc.jpg

sass:
  style: compressed
gems:
  - jekyll-sitemap
